---

- hosts: all
  become: true
  tasks: 
  
  - name: update repo index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install the apache2 & php package
    apt: 
      name:
        - apache2
        - libapache2-mod-php
    when: ansible_distribution == "Ubuntu"
  - name: copy default html file for site
    tags: apache, apache2, httpd
    copy: 
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
